version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventorysales
      MYSQL_USER: admin
      MYSQL_PASSWORD: Satheesh
    ports:
      - "3306:3306"
   volumes:
  - ./logs:/app/logs

  product-service:
    build:
      context: .
    container_name: invsales-product-service
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventorysales
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Satheesh
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
